apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki
  labels:
    name: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.istio-system.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
    - job_name: kubernetes-pods-uday-app
      kubernetes_sd_configs:
      - role: pod

      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_namespace
        regex: uday-app

      - source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod

      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace

      - source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container

      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node

      - action: replace
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: __path__
        replacement: /var/log/pods/*$1/*/*.log

      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_port_number
        regex: (.+)
        replacement: true
        target_label: __scrub_syslog

      pipeline_stages:
      - cri: {}
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z'
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<stream>stdout|stderr) (?P<logtag>\S+) (?P<log>.*)$'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: loki
  labels:
    name: promtail
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail
      hostNetwork: false
      hostPID: true
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
        - istio-system.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      containers:
      - name: promtail
        image: grafana/promtail:2.9.4
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: loki
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: loki
